env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  no-plusplus: 0
  fp/no-this: 0
